name: Auto Assign
on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: ready_for_review
jobs:
  documentation-issue:
    name: Assign Documentation Issue
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            ffelix1
          assignees: |
            ffelix1
          includeLabels: documentation  
          
  bug-issue:
    name: Assign Bug Issue
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            will-spaar
          assignees: |
            will-spaar
          includeLabels: bug
      
