name: Auto Assign Pull Requests
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  assign-pull-request:
    name: Assign Pull Request Reviewer
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            ffelix1
          numberOfReviewers: 1
