name: pull-request
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ffelix1
