name: Move pull request to 'On Deck'
on:
  pull_request_review:
    types: [submitted]
env:
  on_deck: 🔖 On Deck
  
jobs:  
  move-PR-on-deck:
    if: github.event.review.state == 'changes_requested'
    name: return_to_on_deck
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to ${{ env.on_deck }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.PROJECT_ORG_TOKEN }}
          user: will-spaar
          # organization: sample-org
          project_id: 1
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.on_deck }} # Target status
