name: Move issue attached to pull request
on:
  pull_request:
    types:
      - ready_for_review
jobs:
  move-issue-in-review:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Auto Add Issues
          column: In Review
          repo-token: ${{ secrets.ADD_TO_PROJECT }}
