name: Move pull request to 'Ready to Merge'
on:
  pull_request_review:
    types: [submitted]
env:
  ready_to_merge: ✅ Ready to Merge
  
jobs:  
  move-issue-ready-to-merge:
    if: github.event.review.state == 'approved'
    name: ready_for_review
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to ${{ env.ready_to_merge }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.PROJECT_ORG_TOKEN }}
          user: will-spaar
          # organization: sample-org
          project_id: 1
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.ready_to_merge }} # Target status
