name: Move issue attached to pull request
on:
  pull_request:
    types:
      - ready_for_review
env:
  todo: Todo
  done: Done
  in_review: In Review 🎁
  
jobs:
  move-issue-in-review:
    name: ready_for_review
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.PROJECT_ORG_TOKEN }}
          user: will-spaar
          # organization: sample-org
          project_id: 1
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_review }} # Target status
